// Crisis terms — over-trigger intentionally for safety
export const CRISIS_TERMS: string[] = [
  "self-harm",
  "self harm",
  "selfharm",
  "suicide",
  "suicidal",
  "kill myself",
  "killing myself",
  "want to die",
  "wanna die",
  "end it all",
  "end my life",
  "end it",
  "hurt myself",
  "hurting myself",
  "harm myself",
  "harming myself",
  "no reason to live",
  "not worth living",
  "life is not worth",
  "don't want to be here",
  "dont want to be here",
  "do not want to be here",
  "don't want to live",
  "dont want to live",
  "wish i was dead",
  "wish i were dead",
  "better off dead",
  "better off without me",
  "take my own life",
  "taking my own life",
  "end my pain",
  "can't go on",
  "cant go on",
  "can't take it anymore",
  "cant take it anymore",
  "give up on life",
  "giving up on life",
  "overdose",
  "slit my wrists",
  "hang myself",
  "jump off",
  "shoot myself",
  "nobody would miss me",
  "no one would miss me",
  "say goodbye",
  "final note",
  "suicide note",
  "method to kill",
  "ways to kill",
  "how to kill myself",
  "how to end my life",
  "painless way to die",
]

// Temporal markers for news_recent detection
export const TEMPORAL_TERMS: string[] = [
  "today",
  "yesterday",
  "latest",
  "breaking",
  "this week",
  "this month",
  "right now",
  "just happened",
  "just announced",
  "currently",
  "recent",
  "recently",
  "now",
  "at the moment",
  "as of now",
  "last night",
  "this morning",
  "this evening",
  "earlier today",
  "happening now",
  "live update",
  "breaking news",
  "just in",
  "new development",
  "update on",
  "what happened",
  "what is happening",
  "whats happening",
  "what happened with",
  "what happened to",
  "latest news",
  "latest update",
  "current status",
]

// Opinion/subjective markers
export const OPINION_TERMS: string[] = [
  "best",
  "worst",
  "should i",
  "favorite",
  "favourite",
  "overrated",
  "underrated",
  "recommend",
  "recommendation",
  "better than",
  "your opinion",
  "do you like",
  "do you think",
  "do you prefer",
  "greatest",
  "most underrated",
  "most overrated",
  "is it worth",
  "is it good",
  "is it bad",
  "worth it",
  "worth buying",
  "worth watching",
  "worth reading",
  "should i buy",
  "should i watch",
  "should i read",
  "should i use",
  "which is better",
  "what do you think",
  "what is your",
  "rate",
  "rating",
  "rankings",
  "top 10",
  "top ten",
  "must have",
  "must see",
  "must read",
  "love or hate",
]

// Scaffolds to strip — [pattern, kind]
// kind: "what" | "who" | "tell" | "define" | "other"
export const SCAFFOLDS: Array<[RegExp, string]> = [
  [/^what\s+(?:is|are|was|were)\s+(?:the\s+)?/i, "what"],
  [/^what\s+(?:exactly\s+)?(?:is|are|was|were)\s+/i, "what"],
  [/^who\s+(?:is|was|are|were)\s+/i, "who"],
  [/^who\s+(?:exactly\s+)?(?:is|was)\s+/i, "who"],
  [/^where\s+(?:is|are|was|were)\s+/i, "what"],
  [/^when\s+(?:is|are|was|were|did|does|do)\s+/i, "what"],
  [/^why\s+(?:is|are|was|were|did|does|do)\s+/i, "what"],
  [/^how\s+(?:is|are|was|were|did|does|do)\s+(?:(?:you|i|we|one|they|it|he|she)\s+)?/i, "what"],
  [/^how\s+(?:many|much|long|far|old|big|tall|wide|deep|high)\s+(?:is|are|was|were)?\s*/i, "what"],
  [/^tell\s+me\s+(?:about|more\s+about|all\s+about)\s+/i, "tell"],
  [/^can\s+you\s+tell\s+me\s+(?:about\s+)?/i, "tell"],
  [/^could\s+you\s+tell\s+me\s+(?:about\s+)?/i, "tell"],
  [/^please\s+tell\s+me\s+(?:about\s+)?/i, "tell"],
  [/^i\s+want\s+to\s+know\s+(?:about\s+)?/i, "tell"],
  [/^i\s+'d\s+like\s+to\s+know\s+(?:about\s+)?/i, "tell"],
  [/^i\s+need\s+to\s+know\s+(?:about\s+)?/i, "tell"],
  [/^explain\s+(?:to\s+me\s+)?(?:what\s+is\s+|what\s+are\s+)?/i, "tell"],
  [/^describe\s+(?:to\s+me\s+)?/i, "tell"],
  [/^define\s+/i, "define"],
  [/^what\s+does\s+.+?\s+mean\b/i, "define"],
  [/^meaning\s+of\s+/i, "define"],
  [/^definition\s+of\s+/i, "define"],
  [/^please\s+/i, "other"],
  [/^hey[,\s]+/i, "other"],
  [/^hi[,\s]+/i, "other"],
  [/^hello[,\s]+/i, "other"],
  [/^can\s+you\s+/i, "other"],
  [/^could\s+you\s+/i, "other"],
  [/^would\s+you\s+/i, "other"],
  [/^do\s+you\s+know\s+(?:about\s+)?/i, "other"],
]

// Contraction expansion map
export const CONTRACTIONS: Record<string, string> = {
  "whats": "what is",
  "what's": "what is",
  "whos": "who is",
  "who's": "who is",
  "wheres": "where is",
  "where's": "where is",
  "hows": "how is",
  "how's": "how is",
  "whens": "when is",
  "when's": "when is",
  "thats": "that is",
  "that's": "that is",
  "its": "it is",
  "it's": "it is",
  "isn't": "is not",
  "isnt": "is not",
  "aren't": "are not",
  "arent": "are not",
  "wasn't": "was not",
  "wasnt": "was not",
  "weren't": "were not",
  "werent": "were not",
  "don't": "do not",
  "dont": "do not",
  "doesn't": "does not",
  "doesnt": "does not",
  "didn't": "did not",
  "didnt": "did not",
  "can't": "cannot",
  "cant": "cannot",
  "couldn't": "could not",
  "couldnt": "could not",
  "won't": "will not",
  "wont": "will not",
  "wouldn't": "would not",
  "wouldnt": "would not",
  "haven't": "have not",
  "havent": "have not",
  "hasn't": "has not",
  "hasnt": "has not",
  "hadn't": "had not",
  "hadnt": "had not",
  "i'm": "i am",
  "im": "i am",
  "i've": "i have",
  "ive": "i have",
  "i'll": "i will",
  "ill": "i will",
  "i'd": "i would",
  "id": "i would",
  "he's": "he is",
  "hes": "he is",
  "she's": "she is",
  "shes": "she is",
  "they're": "they are",
  "theyre": "they are",
  "we're": "we are",
  "were": "we are",
  "you're": "you are",
  "youre": "you are",
  "they've": "they have",
  "theyve": "they have",
  "we've": "we have",
  "weve": "we have",
  "you've": "you have",
  "youve": "you have",
  "he'd": "he would",
  "hed": "he would",
  "she'd": "she would",
  "shed": "she would",
  "they'd": "they would",
  "theyd": "they would",
  "we'd": "we would",
  "wed": "we would",
  "you'd": "you would",
  "youd": "you would",
  "there's": "there is",
  "theres": "there is",
  "there're": "there are",
  "therere": "there are",
  "let's": "let us",
  "lets": "let us",
}

// Imperative creative verbs
export const CREATIVE_VERBS: string[] = [
  "write",
  "compose",
  "make",
  "generate",
  "create",
  "give me",
  "tell me",
  "craft",
  "produce",
  "come up with",
  "invent",
  "pen",
  "draft",
]

// Creative form nouns
export const CREATIVE_NOUNS: string[] = [
  "poem",
  "story",
  "song",
  "haiku",
  "essay",
  "rap",
  "lyrics",
  "sonnet",
  "limerick",
  "fiction",
  "tale",
  "narrative",
  "short story",
  "short story",
  "verse",
  "rhyme",
  "ode",
  "ballad",
  "prose",
  "paragraph",
  "passage",
  "joke",
  "riddle",
  "fable",
  "myth",
  "legend",
  "anecdote",
  "monologue",
  "dialogue",
  "script",
  "screenplay",
]

// Code language identifiers
export const CODE_LANGS: string[] = [
  "python",
  "javascript",
  "typescript",
  "js",
  "ts",
  "go",
  "golang",
  "rust",
  "java",
  "c++",
  "cpp",
  "c#",
  "csharp",
  "ruby",
  "php",
  "swift",
  "kotlin",
  "sql",
  "bash",
  "shell",
  "sh",
  "html",
  "css",
  "scss",
  "react",
  "vue",
  "angular",
  "node",
  "nodejs",
  "r",
  "scala",
  "perl",
  "lua",
  "dart",
  "elixir",
  "haskell",
  "clojure",
  "lisp",
  "assembly",
  "asm",
  "matlab",
  "fortran",
  "cobol",
  "powershell",
  "vba",
]

// Code-related nouns
export const CODE_NOUNS: string[] = [
  "code",
  "function",
  "script",
  "program",
  "regex",
  "regular expression",
  "query",
  "algorithm",
  "implementation",
  "class",
  "method",
  "snippet",
  "example",
  "solution",
  "module",
  "library",
  "api",
  "endpoint",
  "hook",
  "component",
  "utility",
  "helper",
  "parser",
  "formatter",
  "validator",
  "middleware",
  "decorator",
  "interface",
  "type",
  "schema",
  "migration",
  "test",
  "unit test",
  "integration test",
]

// Weather-related terms
export const WEATHER_TERMS: string[] = [
  "weather",
  "temperature",
  "forecast",
  "rain",
  "raining",
  "snow",
  "snowing",
  "sunny",
  "cloudy",
  "hot",
  "cold",
  "humid",
  "humidity",
  "wind",
  "windy",
  "storm",
  "stormy",
  "thunder",
  "thunderstorm",
  "lightning",
  "fog",
  "foggy",
  "hail",
  "sleet",
  "drizzle",
  "overcast",
  "clear",
  "partly cloudy",
  "precipitation",
  "uv index",
  "feels like",
  "heat index",
  "wind chill",
  "dew point",
  "pressure",
]

// Crypto symbols and names
export const CRYPTO_SYMBOLS: string[] = [
  "btc",
  "eth",
  "bitcoin",
  "ethereum",
  "solana",
  "sol",
  "doge",
  "dogecoin",
  "xrp",
  "ripple",
  "bnb",
  "ada",
  "cardano",
  "avax",
  "avalanche",
  "dot",
  "polkadot",
  "matic",
  "polygon",
  "link",
  "chainlink",
  "uni",
  "uniswap",
  "ltc",
  "litecoin",
  "atom",
  "cosmos",
  "shib",
  "shiba inu",
  "trx",
  "tron",
  "xlm",
  "stellar",
  "algo",
  "algorand",
  "near",
  "ftm",
  "fantom",
  "sandbox",
  "sand",
  "mana",
  "decentraland",
  "axs",
  "axie",
  "usdt",
  "tether",
  "usdc",
  "busd",
  "dai",
]

// Structured fact templates
export const STRUCTURED_FACT_TEMPLATES: Array<{
  pattern: RegExp
  label: string
  properties: string[]
  entityGroup: number
}> = [
  // Height
  {
    pattern: /^(?:how\s+tall\s+is\s+|height\s+of\s+|what\s+(?:is\s+)?the\s+height\s+of\s+)(.+)$/i,
    label: "height",
    properties: ["P2048", "P2049"],
    entityGroup: 1,
  },
  // Age / birthday
  {
    pattern: /^(?:how\s+old\s+is\s+|age\s+of\s+|what\s+(?:is\s+)?the\s+age\s+of\s+)(.+)$/i,
    label: "date of birth",
    properties: ["P569"],
    entityGroup: 1,
  },
  // Birth date
  {
    pattern: /^(?:when\s+was\s+)(.+?)(?:\s+born)$/i,
    label: "date of birth",
    properties: ["P569"],
    entityGroup: 1,
  },
  {
    pattern: /^(?:birth(?:day|date)\s+of\s+|date\s+of\s+birth\s+of\s+)(.+)$/i,
    label: "date of birth",
    properties: ["P569"],
    entityGroup: 1,
  },
  // Death date
  {
    pattern: /^(?:when\s+did\s+)(.+?)(?:\s+die)$/i,
    label: "date of death",
    properties: ["P570"],
    entityGroup: 1,
  },
  {
    pattern: /^(?:death\s+(?:date|day)\s+of\s+|date\s+of\s+death\s+of\s+)(.+)$/i,
    label: "date of death",
    properties: ["P570"],
    entityGroup: 1,
  },
  // Population
  {
    pattern: /^(?:population\s+of\s+|how\s+many\s+people\s+(?:live\s+in|are\s+in)\s+)(.+)$/i,
    label: "population",
    properties: ["P1082"],
    entityGroup: 1,
  },
  // Capital
  {
    pattern: /^(?:capital\s+(?:city\s+)?of\s+|what\s+(?:is\s+)?the\s+capital\s+(?:city\s+)?of\s+)(.+)$/i,
    label: "capital",
    properties: ["P36"],
    entityGroup: 1,
  },
  // Area
  {
    pattern: /^(?:area\s+of\s+|what\s+(?:is\s+)?the\s+(?:total\s+)?area\s+of\s+|how\s+big\s+is\s+)(.+)$/i,
    label: "area",
    properties: ["P2046"],
    entityGroup: 1,
  },
  // Founder
  {
    pattern: /^(?:who\s+founded\s+|founder\s+of\s+|who\s+started\s+|who\s+created\s+)(.+)$/i,
    label: "founded by",
    properties: ["P112"],
    entityGroup: 1,
  },
  // Author / writer
  {
    pattern: /^(?:who\s+wrote\s+|author\s+of\s+|who\s+is\s+the\s+author\s+of\s+)(.+)$/i,
    label: "author",
    properties: ["P50"],
    entityGroup: 1,
  },
  // Director
  {
    pattern: /^(?:who\s+directed\s+|director\s+of\s+|who\s+is\s+the\s+director\s+of\s+)(.+)$/i,
    label: "director",
    properties: ["P57"],
    entityGroup: 1,
  },
  // Inventor
  {
    pattern: /^(?:who\s+invented\s+|inventor\s+of\s+|who\s+is\s+the\s+inventor\s+of\s+)(.+)$/i,
    label: "inventor",
    properties: ["P61"],
    entityGroup: 1,
  },
  // Net worth
  {
    pattern: /^(?:net\s+worth\s+of\s+|how\s+(?:rich|wealthy)\s+is\s+|what\s+(?:is\s+)?the\s+net\s+worth\s+of\s+)(.+)$/i,
    label: "net worth",
    properties: ["P2218"],
    entityGroup: 1,
  },
  // Founded date
  {
    pattern: /^(?:when\s+was\s+)(.+?)(?:\s+founded)$/i,
    label: "inception",
    properties: ["P571"],
    entityGroup: 1,
  },
  {
    pattern: /^(?:founding\s+(?:date|year)\s+of\s+|when\s+(?:did|was)\s+)(.+?)(?:\s+(?:start|begin|launch|found))(?:ed)?$/i,
    label: "inception",
    properties: ["P571"],
    entityGroup: 1,
  },
  // Release date
  {
    pattern: /^(?:when\s+was\s+)(.+?)(?:\s+released)$/i,
    label: "publication date",
    properties: ["P577", "P571"],
    entityGroup: 1,
  },
  {
    pattern: /^(?:release\s+date\s+of\s+|when\s+did\s+)(.+?)(?:\s+(?:come\s+out|release|launch))$/i,
    label: "publication date",
    properties: ["P577", "P571"],
    entityGroup: 1,
  },
  // Programming language
  {
    pattern: /^(?:what\s+(?:programming\s+)?language\s+(?:is\s+|was\s+)?|written\s+in\s+what\s+language\s*[—-]?\s*)(.+?)(?:\s+written\s+in)?$/i,
    label: "programming language",
    properties: ["P277"],
    entityGroup: 1,
  },
  {
    pattern: /^(?:what\s+language\s+is\s+)(.+?)(?:\s+written\s+in)$/i,
    label: "programming language",
    properties: ["P277"],
    entityGroup: 1,
  },
  // CEO
  {
    pattern: /^(?:who\s+is\s+the\s+(?:ceo|chief\s+executive\s+officer)\s+of\s+|ceo\s+of\s+)(.+)$/i,
    label: "chief executive officer",
    properties: ["P169"],
    entityGroup: 1,
  },
  // Headquarters
  {
    pattern: /^(?:headquarters\s+of\s+|where\s+(?:is|are)\s+)(.+?)(?:['']s?\s+headquarters|\s+headquartered|\s+based)$/i,
    label: "headquarters location",
    properties: ["P159"],
    entityGroup: 1,
  },
]
